### ISSUE TITLE
Yaml dans Patagui

### ISSUE THREAD

**Issue by LaTruelle** [patacrep/patacrep#201]
Comme vous travaillez à passer à yaml dans patacrep, je suis en train de l'incorporer dans patagui. pour l'instant j'arrive raisonnablement à écrire un songbook je n'ai pas essayé la lecture mais ça devrait le faire en temps et en heure. 

Par contre, j'ai l'impression qu'au passage, il y a pas mal d'autres choses qui ont été changées dans patacrep ? Le script qui suit utilisé avec la branche "yaml" de patacrep me renvoie des erreurs bizarres de structure de songbook.

Mon script: (l'important qui plante, c'est la fonction setupSongbook(songbook_path, datadir))
```
#!/usr/bin/env python
# -*- coding: utf-8 -*-

# Import all required modules
import yaml
import locale
import os.path
import textwrap
import sys
import logging
import threading

# Import patacrep modules
from patacrep.build import SongbookBuilder, DEFAULT_STEPS
from patacrep import __version__
from patacrep import errors
import patacrep.encoding

# Expose C++ to local python
# from PythonQt import *

# Define global variables
sb_builder = None
process = None
stopProcess = False
# logging.basicConfig(level=logging.DEBUG)


# Define locale according to user's parameters
def setLocale():
    try:
        locale.setlocale(locale.LC_ALL, '')
    except locale.Error as error:
        print("Locale Error")
        # Throw error


# Test patacrep version
def testPatacrep():
    return patacrep.__version__


def message(text):
    # CPPprocess.message(text, 0)
    print(text)


# Load songbook and setup datadirs
def setupSongbook(songbook_path, datadir):
    setLocale()
    global sb_builder
    basename = os.path.basename(songbook_path)[:-3]
    # Load songbook from sb file.
    try:
        with patacrep.encoding.open_read(songbook_path) as songbook_file:
            songbook = yaml.load(songbook_file)
        if 'encoding' in songbook:
            with patacrep.encoding.open_read(songbook_path,
                                             encoding=songbook['encoding'])\
                                             as songbook_file:
                songbook = json.load(songbook_file)
    except Exception as error:  # pylint: disable=broad-except
        print("Error while loading file '{}'".format(songbook_path))
        print(error)
        # Throw Exception
        return

    # Gathering datadirs
    datadirs = []
    if 'datadir' in songbook:
        # .sg file
        if isinstance(songbook['datadir'], str):
            songbook['datadir'] = [songbook['datadir']]
        datadirs += [
            os.path.join(
                os.path.dirname(os.path.abspath(songbook_path)),
                path
                )
            for path in songbook['datadir']
            ]
    # Default value
    datadirs.append(os.path.dirname(os.path.abspath(songbook_path)))
    songbook['datadir'] = datadirs
    songbook['_basename'] = os.path.basename(songbook_path)[:-3]
    try:
        sb_builder = SongbookBuilder(songbook)
        sb_builder.unsafe = True
    except errors.SongbookError as error:
        print("Error in formation of Songbook Builder")
        print(error)
        # Deal with error


# Wrapper around buildSongbook that manages the threading part
def build(steps):
    global stopProcess
    global process
    stopProcess = False
    process = threading.Thread(target=buildSongbook, args=(steps,))
    try:
        # logger.info('Starting process')
        process.start()
    except threading.ThreadError as error:
        # logger.warning('process Error occured')
        message(error)

    period = 2
    while process.is_alive():
        # message("it's alive: " + CPPprocess.getBuildState())
        # if not CPPprocess.getBuildState():
        #     try:
        #         process.crash()
        #     except AttributeError as error:
        #         message("Building exited at user's request")
        #         raise
        # # Check in 2 seconds
        process.join(period)
    message("end build")


# Inner function that actually builds the songbook
def buildSongbook(steps):
    global sb_builder
    # message("Inner Function Reached")
    sys.stdout.flush()
    try:
        for step in steps:
            message("Building songbook: " + step)
            sb_builder.build_steps([step])
        message("Building finished")
    except errors.SongbookError as error:
        message("Building error")
        # Call proper function in CPPprocess
        message(error)
        raise
    # message("Exiting buildSongbook function")


def stopBuild():
    message("Terminating process")
    global stopProcess
    stopProcess = True

setupSongbook("/Users/emmanuel/testingSongbook/aa.sb",
              "/Users/emmanuel/testingSongbook/")
build(['tex'])
build(['pdf'])
```

Mon songbook: (avec des chants par défauts, compile ok si j'utilise l'utilitaire `songbook`)
```
book:
  pictures: yes
  datadir: /path/to/datadir
  lang: en
  template: patacrep.tex
chords:
  repeatchords: no
  diagramreminder: all
content:
  - chevaliers_de_la_table_ronde.sg
  - example-en.sg
  - example-fr.sg
  - greensleeves.sg
  - test_plastex.sg
  - vent_frais.sg
```

Mes messages d'erreur:
```
Error in formation of Songbook Builder
The songbook file 'aa' is not valid
does not match schema:
  missing required fields:
    titles
    _songdir
    _datadir
    _filepath
    authors
    _error
    _cache
  unknown field: 'datadir'
  'chords' missing required fields:
    show
    notation
    lilypond
    instrument
    tablatures
    diagrampage
  'book' does not match schema:
    missing required fields: onesongperpage, encoding
    unknown field: 'datadir'
Building songbook: tex
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "songbook.py", line 129, in buildSongbook
    sb_builder.build_steps([step])
AttributeError: 'NoneType' object has no attribute 'build_steps'

end build
Building songbook: pdf
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "songbook.py", line 129, in buildSongbook
    sb_builder.build_steps([step])
AttributeError: 'NoneType' object has no attribute 'build_steps'

end build
```
La fin c'est normal, il a planté au début...

**Comment by oliverpool** [comment]
C'est parce que j'ai implémenté la vérification du carnet au mauvais endroit.
Je vais creuser un peu et je te tiens au courant !

**Comment by oliverpool** [comment]
Je me suis mépris, je pensais que tu voulais générer le carnet sans avoir de fichier songbook.

Je pense que tu devrais changer ta fonction setupSongbook pour te rapprocher de https://github.com/patacrep/patacrep/blob/yaml/patacrep/songbook/__main__.py#L148-L160

**Comment by oliverpool** [comment]
@LaTruelle le plus gros du travail de `yaml` est désormais mergé dans `master` ! (seul un petit changement sur `cwd` est à venir https://github.com/patacrep/patacrep/issues/204, mais rien de génat pour toi)

**Comment by LaTruelle** [comment]
Cool, merci pour l'info !
