### ISSUE TITLE
Emplacement datadir et output

### ISSUE THREAD

**Issue by MoeNadal** [patacrep/patacrep#259]
Bonjour a tous!

Tout d'abord, un grand merci a tous les mainteneurs (anciens et nouveaux), patacrep est un projet vraiment cool et le rendu est vraiment trop bien. Et du coup voir qu'il y a du monde pour prendre le relais est très appréciable (et apprécié). 

Je suis en train de tripatouiller un peu le code en ce moment (petit projet d'interface web devant patacrep pour mon popa qui aime beaucoup la musique mais qui n'est pas ultra technique ^^) et j'ai identifier deux bugs qui peuvent être problématique:

- Probleme pour définir un datadir. Le format indiqué dans la doc ne fonctionne pas, et si on tente de feinter, ça ne marche quand même pas. 
          * Argument --datadir consomme l'argument book en ligne de commande, ex : 
```$ songbook --datadir patacrep_data/ songbook_test.yaml 
usage: songbook [-h] [--version] [--datadir DATADIR [DATADIR ...]] [--verbose]
                [--cache CACHE] [--error {failonsong,failonbook,fix}]
                [--steps STEPS]
                book
songbook: error: the following arguments are required: book```
          *Premier test, mettre le book avant : 
```$ songbook songbook_test.yaml --datadir patacrep_data/
Traceback (most recent call last):
  File "/home/babcool/dev/java/workspace/flaskapate/venv/bin/songbook", line 11, in <module>
    load_entry_point('patacrep==5.1.2', 'console_scripts', 'songbook')()
  File "/home/babcool/dev/java/workspace/flaskapate/venv/lib/python3.5/site-packages/patacrep/songbook/__main__.py", line 153, in main
    songbook['datadir'].insert(0, datadir)
KeyError: 'datadir'```
Et intercaler un `--verbose` après le datadir permet d'eviter le probleme du book non reconnu, mais aboutit a la même erreur (commande `$ songbook --datadir patacrep_data/ --verbose songbook_test.yaml` )

- Deuxieme bug, moins important, je n'ai pas réussi à définir programmatiquement le dossier d'output. L'option outputdir de la méthode prepare_songbook semble ignorée et le fichier est toujours produit dans le cwd courant (j'ai finit par faire un chdir avant l'appel a build_steps() ). 
La seule manière de feinter que j'ai trouvé est de mettre un chemin complet dans outputname, mais ça provoque une erreur lors de la compilation du latex lors de l'écriture des fichier sbx. 

Voila un bout du code que j'utilise pour générer le pdf : 
```python
def get_yaml_songbook(songbook:Songbook, patacrep_config:PatacrepConfig):

    loader = FileSystemLoader(patacrep_config.yaml_template_folder)

    env = Environment(loader=loader,
                      autoescape=select_autoescape(['yaml']))
    template = env.get_template("base.yaml")
    yaml_string = template.render(songbook=songbook)
    print(yaml_string)
    yaml_songbook = yaml.load(yaml_string)
    yaml_songbook["book"]["datadir"] = patacrep_config.datadir
    result = prepare_songbook(songbook=yaml_songbook,
                              outputdir=patacrep_config.output_dir,
                              outputname="songbook_test2",
                              datadir_prefix=patacrep_config.datadir)
    result['_cache'] = patacrep_config.use_cache
    result['_error'] = patacrep_config.error_mode
    return result


def generate_songbook(songbook, patacrep_config):
    songbook_patacrep = get_yaml_songbook(songbook, patacrep_config)
    sb_builder = SongbookBuilder(songbook_patacrep)
    sb_builder.unsafe = True
    os.chdir(patacrep_config.output_dir)
    sb_builder.build_steps() 
```

**Comment by takuyozora** [comment]
Je confirme avoir également rencontré l'erreur lié aux datadir.

**Comment by oliverpool** [comment]
Quel est le contenu du fichier `songbook_test.yaml` ?
