### ISSUE TITLE
Jinja dependency error

### ISSUE THREAD

**Issue by OrianeN** [patacrep/patacrep#273]
After installing patacrep, I launched the command `songbook --version` and got the following output:

> Traceback (most recent call last):
  File "C:\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\Users\Oriane\OneDrive\Documents\Code\songs_patacrep_poc\venv\Scripts\songbook.exe\__main__.py", line 4, in <module>
  File "d:\users\oriane\onedrive\documents\code\songs_patacrep_poc\venv\lib\site-packages\patacrep\songbook\__init__.py", line 9, in <module>
    from patacrep.build import config_model
  File "d:\users\oriane\onedrive\documents\code\songs_patacrep_poc\venv\lib\site-packages\patacrep\build.py", line 13, in <module>
    from patacrep import authors, content, encoding, errors, pkg_datapath, utils
  File "d:\users\oriane\onedrive\documents\code\songs_patacrep_poc\venv\lib\site-packages\patacrep\content\__init__.py", line 205, in <module>
    @jinja2.contextfunction
**AttributeError: module 'jinja2' has no attribute 'contextfunction'**

I have jinja2==3.1.1 installed.

I've searched the error message and found this: https://githubhot.com/repo/aimhubio/aim/issues/1581 which shows the same error with Jinja2==3.1.0, and advices to install Jinja2==3.0

I've tried replacing the jinja2 library installed in my site-packages by jinja2==3.0.3 and it's working.

I guess the repo should require jinja2==3.0, or change the decorator call.

**Comment by Grahack** [comment]
Thanks for the report.

In the comments section of the issue you link us to (aimhubio) there also is this possibility: « *restrict the Jinja2 version to <3.1.0* » which to me should be the quick fix.

But if you have some time to test could you please try what may be the correct fix (documented [here](https://github.com/django-waffle/django-waffle/issues/402))?
* reinstall jinja 3.1.1;
* rename `contextfunction` to `pass_context`;
* test.

**Comment by Flore-mozfr** [comment]
Bonjour,
J'ai résolu ce problème en remplaçant toutes les occurrences de pass_context par contextfunction dans les fichiers py de patacrep.
Et je n'ai plus l'erreur.

**Comment by sgelis** [comment]
Fixed by #278.
